### ISSUE TITLE
Request alternative/different letter or phone formats

### ISSUE THREAD

**Issue by julieabbo** [dwp/design-system-backlog#86] opened 2022-01-19 14:19 UTC
EDIT: may duplicate https://github.com/dwp/design-system/issues/426

## What
A standard design pattern for people to request different communication methods for example, large print or Relay 

## Why
It is a common question used on most digital services and should be standard across the DWP. 
>
Currently JSA and ESA are working on the same project and are finding that they are designing a similar pattern. 
User research is currently ongoing. 

## Anything else
https://github.com/dwp/design-system-community-backlog/discussions/84
https://github.com/dwp/design-system-community-backlog/issues/59
https://github.com/dwp/design-system/issues/426

**Comment by martinwake** [comment] 2022-01-19 14:37
This suggests a pattern for users to request alternative formats, as in [this discussion](https://github.com/dwp/design-system-community-backlog/discussions/84)

The related backlog item dwp/design-system-community-backlog#59 looks like it relates to agent-facing services so is not quite the same, but perhaps it will make sense to merge these in future.

**Comment by martinwake** [comment] 2022-01-26 15:38
Duplicate of dwp/design-system#426 - closing issue

**Closed as completed by martinwake** 2022-01-26 15:38 UTC
Labels: pattern
